package GUI;

import javax.swing.JOptionPane;
import Controllers.DBManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author luiz
 */
public class ExcluirGUI extends javax.swing.JFrame {

    /**
     * Creates new form InserirGUI
     */
    public ExcluirGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        opcaoCodigo = new javax.swing.JRadioButton();
        opcaoNome = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        textField = new javax.swing.JTextField();
        cancelarBtn = new javax.swing.JButton();
        excluirBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Excluir produto - Multisono Produtos Musicais");
        setBounds(new java.awt.Rectangle(600, 300, 500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radioGroup.add(opcaoCodigo);
        opcaoCodigo.setText("Código");
        getContentPane().add(opcaoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        radioGroup.add(opcaoNome);
        opcaoNome.setText("Nome");
        getContentPane().add(opcaoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel1.setText("Você deseja excluir através do código ou nome?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));
        getContentPane().add(textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 170, -1));

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 120, 50));

        excluirBtn.setText("Excluir");
        excluirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirBtnActionPerformed(evt);
            }
        });
        getContentPane().add(excluirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 120, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void excluirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirBtnActionPerformed
        // TODO add your handling code here:
        DBManager db = new DBManager();

        if (this.opcaoNome.isSelected()) {
            db.excluirNome(this.textField.getText());
        } else if (this.opcaoCodigo.isSelected()) {
            db.excluir(Integer.parseInt(this.textField.getText()));
        }
    }//GEN-LAST:event_excluirBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JButton excluirBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton opcaoCodigo;
    private javax.swing.JRadioButton opcaoNome;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
